---
# ===================
#      DAMAGE TP 
# ===================
# 1. A simple plugin to teleport the player to world spawn when taking damage!
# 2. If you see errors, report here: https://github.com/Henry12960/DamageTP/issues/new
# 3. Plugin made by Henry Thierry [HenryDM] 
# 4. Henry's Website: https://github.com/Henry12960

# ===================
#       GENERAL 
# ===================
# NOTE: 'damage-to-world's' are the world's where this plugin works!

damage-tp-worlds: ["lobby", "world"]

# ===================
#      DAMAGES 
# ===================
# 1. Set to true to enable the ones you prefer!

tp-spawn-projectile: false
tp-spawn-suffocation: false
tp-spawn-fall: false
tp-spawn-lava: false
tp-spawn-drowning: false
tp-spawn-explosion: false
tp-spawn-void: false
...